In [1]:
import pandas as pd

In [2]:
df = pd.read_json('/content/drive/MyDrive/messages.json')

In [3]:
df.head(40)

,userId,exportDate,conversations
0,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.2ce9f8dccf1fc085', 'displa..."
1,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.78533d4cb35406cc', 'displa..."
2,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.a4c67d0b2e72bac6', 'displa..."
3,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.354621f1f9cfe2ea', 'displa..."
4,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:mayanktamboli', 'displayName': ..."
5,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.72f5ade725d5c5f6', 'displa..."
6,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:rkt7k2', 'displayName': 'Rithik..."
7,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.b78a08ecf7265b9', 'display..."
8,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.64a4920113acc63c', 'displa..."
9,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:ankursingh037', 'displayName': ..."
10,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:arpitchamp1996', 'displayName':..."
11,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:sushant_sur23', 'displayName': ..."
12,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.f2c3e8ddc28618a0', 'displa..."
13,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.11e1b22d5d6abe2c', 'displa..."
14,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '48:calllogs', 'displayName': None, 've..."
15,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.b7498b6801dc7a6e', 'displa..."
16,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:sudheer.ece2008', 'displayName'..."
17,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.539acecc3b5404db', 'displa..."
18,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:anupkolkata30_2', 'displayName'..."
19,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:abhishekmalviya8888', 'displayN..."
20,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:4e276427f5a68736', 'displayName..."
21,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.454fef0bd7c1d8fa', 'displa..."
22,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.682d1c68cbcbaf0', 'display..."
23,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.245f03148e95508d', 'displa..."
24,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.4087071abd3b046a', 'displa..."
25,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.dea33e1917de9c56', 'displa..."
26,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.7c188df71769c1dc', 'displa..."
27,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:nawabtajhasan.thm', 'displayNam..."
28,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:7e4920def2e28cae', 'displayName..."
29,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.da336d8f16c8aadd', 'displa..."
30,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:nihcas.kmr', 'displayName': 'sa..."
31,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.cb48c9682b598273', 'displa..."
32,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.a0d2076b44f40466', 'displa..."
33,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.e96a0ae5380b4d45', 'displa..."
34,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.9b20612702226104', 'displa..."
35,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.faf8d421b5e1bcbc', 'displa..."
36,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.84f474e554fba245', 'displa..."
37,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:6678f8c6c5db8970', 'displayName..."
38,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:aravind200113', 'displayName': 'arav..."
39,8:live:.cid.4933a22bf564744,2022-06-11T00:06,"{'id': '8:live:.cid.b0c5c440bb57de49', 'displa..."

In [9]:
# df.drop(['userId','exportDate'], axis=1)
convo = df['conversations']

In [11]:
ans= pd.DataFrame()

convo_iter = convo[2]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,hello sir .,first if it is possible
1,thank you!!\r,you can download
2,not yet,welcome
3,Ok,you need not bother abou the navigator
4,Hmm,your jupyter notebook is working fine
5,Install..,okay sir
6,Ok i will re do the things again,please give it some time
7,I click on second one,for the navigator to open
8,I did it several times sir,it will take some time sir
9,How to do that,are you able to write your code in jupyter not...

In [12]:
convo_iter = convo[1]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,ok,Big Data Course will be launched soon
1,Ok sir.,appear for the screening test and later you ca...
2,Is the degree compulsory for most of the compa...,at least a bachelor degree might be required
3,He just passed 12th,I guess so
4,for my small brother,but later it may be mandatory as per the compa...
...,...,...
76,The last cell never stops running and I can&ap...,What issues are you facing sir
77,,try to use 3.6 sir
78,Ok so I cant join now,which python version have you used hare sir?
79,It is showing that The host has another meetin...,which project you&apos;re doing sir
80,I already checked it,can you send ss when you installed what came

In [13]:
convo_iter = convo[3]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,already installed,send me screenshot of installed app
1,windows 10,search anaconda and send me screenshot
2,need help for download anaconda,what you are not getting
3,It&apos;s updated but not working .. already t...,send me screen shot
4,Yes please,install anaconda
5,Many times I have done it,which os
6,Yes video is here but when I click no one is play,Hello Shakshi
7,Full stack data science,"because on our end, it is updated"
8,Hi,ma&apos;am try checking from a different wi-fi...

In [14]:
convo_iter = convo[4]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,If you just read few texts fromfrom above u wo...,which content you&apos;re looking sir?
1,"So, when will I get that content?",we will connect tomorrow
2,You can text me on 7974716229 (whatsapp),yes
3,"You tell me sir, where are power bi, SQL, tabl...",can we have quick call on this number: 6280963...
4,Sent text and completely ignored after reading...,Shivan this side
5,What&apos;s the name of the person whose conta...,Hello sir
6,Connect where WhatsApp?,we will help you
7,When can I expect the answer??,please connect to +91 6260 726 925 this contac...
8,When?,okay sir. I understood your problem
9,There are no video recordings available of liv...,"Sir, may you please tell us what exactly you w..."
10,"Ok, will wait for SQL live classes",yes sir in office hours only
11,In Full stack will there be live SQL class or ...,you can call here as well sir
12,Did you check?,Kindly connect here sir: +91 6260 726 925
13,"Please do so, it&apos;s been days",we will contact you soon regarding the issue sir
14,Did you ask for the access?,hello sir i will pass your message to our team.
15,"Please do it as soon as possible, just SQL tut...",sir please wait there will be live classes soon
16,Earlier I didn&apos;t know that I could do Bus...,ok
17,Just for SQL I will buy a new coursecourse😢,live classes and recording also
18,"They provided I know, can you see the chat whi...",you have to follow full stack
19,I just want SQL class,sir it will not be possible
20,It is asking for payment,ok sir
21,Business Analytics course where I can find sql...,no update yet will check once again sir
22,I followed MS Sql Server lectures then only te...,ok
23,I&apos;m enrolled in Full Stack Batch and I co...,ok will check and update you
24,Thanks,you can check other resources
25,Please try to upload the Statistics class note...,sorry sir but you have to purchase it
26,"ok, got it. Thanks",so in fullstack they will only provide recordi...
27,ok. so we have to write the questions also in ...,you have to do payment
28,We have to solve and submit the python assignm...,yes sir

In [15]:
convo_iter = convo[5]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,ok sir,*
1,ya,there
2,ya,you can understand from their
3,feb 2022,TOmorrow 10 AM I will exmplain new deployment way
4,should i delete in github and then repost it?,Wait
5,already saved it,nov 2021
6,no pywin32 in requirements.txt,feb 2021
7,there is no lib in reuirements.txt,Tell me your batch name
8,ok,No
9,ok,which batch?
10,so what to do?,send your changes to github then
11,ok,have you upadated your changes to git
12,run procedure is correct as i do?,send screenshot again
13,means?,first
14,pycharm,save your changes
15,django.core.exceptions.ImproperlyConfigured: R...,Now deploy it again and send me screenshot
16,please suggest me about error. where is error?,it told you to remove pywin32
17,here views file,Screeshot of erro
18,not working,send me screenshot
19,what do you mean?,It will be installed due to some other library...
20,yes 3,that is causing this issue
21,3.0.14,remove the lib
22,from django.urls import path\nfrom . import vi...,delete line number 13 and 14
23,ok,pypiwin33
24,still same error,Remote lib name from requirements.txt file
25,ok,so remove this requirement
26,still showing this error,heroku has linux machine you can not install it
27,condition already satisfied.. is showing,it&apos;s only for window
28,ok let me check...pip install jupyter ...shoul...,you will get it solve
29,con not install name &quot;to_html&quot;,Do refer first solution
30,some html error showing.,Try to convert your ndarray with tolist() method
31,yes,you will get it solved
32,no they didnt mentioned it... simplly told to ...,restart you notebook kernal and run all cells ...
33,"i am doing it in anacoconda, jupytrt notebook.",ya
34,Ok,and correct it first before executing whole
35,"Hello,\nI have already filled form for mentor....",check every imports one by one in ur file
36,ok,no resources
37,ok let me check it.,to run these project
38,Thanx,what r u refering
39,ok,what is error now?
40,i am trying but it is not able to reinstall.,Response
41,ok,capital R
42,again?,that is coming from here
43,it is showing this.,yes
44,already i have open it,it is error from views.py import
45,clicked,import views directly it will work
46,yes,import views
47,ok,"there is sub folder ,"
48,ok...thanx,from ProjectTextUtils.ProjectTextUtils import...
49,yes,which version of djanog you are using
50,"no, self is pointer",go through this once the n
51,Ok thanx,which solutins have you checked
52,ok,you can refer here
53,good afternoon,from ProjectTextUtils import views

In [16]:
convo_iter = convo[6]
student = []
teacher = []
for i in range(len(convo_iter['MessageList'])):
    if convo_iter['MessageList'][i]['from'] == '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i]['content']:
      teacher.append(convo_iter['MessageList'][i]['content'])
      if convo_iter['MessageList'][i-1]['from'] != '8:live:.cid.4933a22bf564744' and '<' not in convo_iter['MessageList'][i-1]['content']:
        student.append(convo_iter['MessageList'][i-1]['content'])
ans.append( pd.DataFrame(
    {'student': student,
    'teacher': teacher[0:len(student)]
    }), ignore_index=True)

,student,teacher
0,hmmm. yeah regularization would definitely be ...,use regularization also number of records you ...
1,let me explain u the case sir\ni have a datase...,you shuffle your data set and try again
2,hey sir\nhave a query please\n\nwhen we train ...,It&apos;s experiment
3,"hmm, and then once selected , what if i reject...",It is not explainable
4,means we cant have multiple referrals / offers...,if my model is not performing good on training...
...,...,...
106,yes sir. I thought so.\nI created the reposito...,anything is fine send me colab
107,Hey sir\nGood evening,doe showing any error after excuting
108,sir just while going th. lecture got an error\...,can you send me on which its not applying
109,oh okay . Got that. Thanks for the update sir 👍,refer this how to remove am an dpm
110,ohkay. was wondering because solutions in .ipy...,let me check